[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"
  JWT_SECRET = "restart-jwt-secret-key-2024"
  NEXTAUTH_SECRET = "restart-nextauth-secret-2024"
  NEXTAUTH_URL = "https://restartquiro.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]